{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"amostra_evg\",\"F_matricula\",\"Dim_turma\",\"Dim_curso\",\"Dim_pessoa\",\"Dim_poder\",\"Dim_esfera\",\"Dim_localidade\",\"Dcalendar\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "1023245a-a0dd-4e9c-aca9-136e2f3be1fe",
        "fromColumn": "dt_matricula",
        "fromTable": "amostra_evg",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_630266ad-3423-414a-8136-5f9ed7acacf0"
      },
      {
        "name": "b905d6bd-85b9-47f9-81d1-1a20bf0dade9",
        "fromColumn": "dt_fim",
        "fromTable": "amostra_evg",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_cc536f87-0eba-402d-b5c5-33db04e48925"
      },
      {
        "name": "39d9e91f-dff4-4d71-9fd8-1dd71ef822e0",
        "fromColumn": "data",
        "fromTable": "Dcalendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_dc1ef290-ff20-43ca-9327-1f008f9b1264"
      },
      {
        "name": "042f49a3-e63c-4f5d-821b-0744c4ed9992",
        "fromColumn": "dt_matricula",
        "fromTable": "F_matricula",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6b7251f7-6662-49c8-b1a3-9d7213045187"
      },
      {
        "name": "a7e73bcb-0777-43e0-9805-e3fd9cbeed60",
        "fromColumn": "dt_fim",
        "fromTable": "F_matricula",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b3816c51-0a65-40e0-a5c6-5dc2be8a9148"
      },
      {
        "name": "AutoDetected_b65eddec-631e-4463-816b-7214c3b2ef43",
        "fromColumn": "cod_poder",
        "fromTable": "F_matricula",
        "toColumn": "cod_poder",
        "toTable": "Dim_poder"
      },
      {
        "name": "AutoDetected_3f0c55c5-8326-4b6b-9a89-e1304aa9b628",
        "fromColumn": "cod_esfera",
        "fromTable": "F_matricula",
        "toColumn": "cod_esfera",
        "toTable": "Dim_esfera"
      },
      {
        "name": "AutoDetected_d615816a-9ad7-4534-aa66-d0c6874b5cbd",
        "fromColumn": "Cod_localidade",
        "fromTable": "F_matricula",
        "toColumn": "Cod_localidade",
        "toTable": "Dim_localidade"
      },
      {
        "name": "00ec0908-13f9-b167-e639-0673b8921c8c",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "codigo_pessoa",
        "fromTable": "Dim_pessoa",
        "toCardinality": "many",
        "toColumn": "codigo_pessoa",
        "toTable": "F_matricula"
      },
      {
        "name": "01a63b42-692c-e7e1-aff5-cce15ca247d0",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "cod_turma",
        "fromTable": "Dim_turma",
        "toCardinality": "many",
        "toColumn": "cod_turma",
        "toTable": "F_matricula"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "amostra_evg",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "cod_matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c17fcc91-4d93-497e-8c7f-843f03c492e8",
            "sourceColumn": "cod_matricula",
            "summarizeBy": "none"
          },
          {
            "name": "dt_matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b946daac-ff1a-43a2-ad1e-92a2f713e32a",
            "sourceColumn": "dt_matricula",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_630266ad-3423-414a-8136-5f9ed7acacf0"
                },
                "isDefault": true,
                "relationship": "1023245a-a0dd-4e9c-aca9-136e2f3be1fe"
              }
            ]
          },
          {
            "name": "nacionalidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d44939f-19e5-49ce-8206-40d529823941",
            "sourceColumn": "nacionalidade",
            "summarizeBy": "none"
          },
          {
            "name": "cod_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d5db3132-222b-4bdd-8641-bb152709fd45",
            "sourceColumn": "cod_turma",
            "summarizeBy": "sum"
          },
          {
            "name": "nome_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c0e183d-ba8c-4674-87f5-4c3e52d436b6",
            "sourceColumn": "nome_turma",
            "summarizeBy": "none"
          },
          {
            "name": "modalidade_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12810131-04d1-47f9-ac62-4d8f69a480a6",
            "sourceColumn": "modalidade_turma",
            "summarizeBy": "none"
          },
          {
            "name": "cod_curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "216464e7-44a5-483d-823b-504e0f7c2eb0",
            "sourceColumn": "cod_curso",
            "summarizeBy": "sum"
          },
          {
            "name": "nome_curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "104f6eb4-6c8f-408e-837a-8437b800574b",
            "sourceColumn": "nome_curso",
            "summarizeBy": "none"
          },
          {
            "name": "carga_horaria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e0908494-5b44-4c86-991d-023cb73e70b7",
            "sourceColumn": "carga_horaria",
            "summarizeBy": "sum"
          },
          {
            "name": "dt_fim",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "cf4cb80c-c8f1-4604-8c6c-5ff2ee81fdf7",
            "sourceColumn": "dt_fim",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_cc536f87-0eba-402d-b5c5-33db04e48925"
                },
                "isDefault": true,
                "relationship": "b905d6bd-85b9-47f9-81d1-1a20bf0dade9"
              }
            ]
          },
          {
            "name": "sit_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e00e769a-8bc9-40f6-a646-df0df2616ee1",
            "sourceColumn": "sit_turma",
            "summarizeBy": "none"
          },
          {
            "name": "instituicao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f40fe195-6195-4297-b443-8298f1c4adfb",
            "sourceColumn": "instituicao",
            "summarizeBy": "none"
          },
          {
            "name": "municipio_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b151d347-ce30-40d5-a866-1ff3e7efb253",
            "sourceColumn": "municipio_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "uf_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b52c2c0c-7d26-40b2-b48a-7f8b8b68de5c",
            "sourceColumn": "uf_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "conteudista",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "157c4026-a36f-4cec-ab41-57c93f56e945",
            "sourceColumn": "conteudista",
            "summarizeBy": "none"
          },
          {
            "name": "tematica",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2cd364e7-9486-4433-bfdd-ef06d9c324aa",
            "sourceColumn": "tematica",
            "summarizeBy": "none"
          },
          {
            "name": "codigo_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "194220fe-e249-4133-9746-1fe12e2a0fbf",
            "sourceColumn": "codigo_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "sexo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a66e76bb-e7f8-4930-9411-37928e5c8809",
            "sourceColumn": "sexo",
            "summarizeBy": "none"
          },
          {
            "name": "idade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b07a0905-218b-4d8d-83eb-754573f2b26a",
            "sourceColumn": "idade",
            "summarizeBy": "sum"
          },
          {
            "name": "sit_matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c224e9f-7d49-48d1-9123-ccd1e99fe926",
            "sourceColumn": "sit_matricula",
            "summarizeBy": "none"
          },
          {
            "name": "poder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f184a754-d482-4379-b30f-731c39a871ec",
            "sourceColumn": "poder",
            "summarizeBy": "none"
          },
          {
            "name": "esfera",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35543e4d-a603-4fa8-866d-13a2325d62a0",
            "sourceColumn": "esfera",
            "summarizeBy": "none"
          },
          {
            "name": "email_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0958104c-33ec-4789-994f-2fae7cc965e9",
            "sourceColumn": "email_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "telefone_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "922aeeac-999b-48b4-918c-257b67a4986d",
            "sourceColumn": "telefone_pessoa",
            "summarizeBy": "sum"
          },
          {
            "name": "email_conteudista",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8b16662-c314-4347-ad2a-3a81d7a66e5f",
            "sourceColumn": "email_conteudista",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0fc7ddf6-47a3-40da-921e-924f6187e914",
        "partitions": [
          {
            "name": "amostra_evg",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\matheushenriquesda\\Downloads\\amostra_evg.csv\"),[Delimiter=\",\", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"cod_matricula\", type text}, {\"dt_matricula\", type datetime}, {\"nacionalidade\", type text}, {\"cod_turma\", Int64.Type}, {\"nome_turma\", type text}, {\"modalidade_turma\", type text}, {\"cod_curso\", Int64.Type}, {\"nome_curso\", type text}, {\"carga_horaria\", Int64.Type}, {\"dt_fim\", type datetime}, {\"sit_turma\", type text}, {\"instituicao\", type text}, {\"municipio_pessoa\", type text}, {\"uf_pessoa\", type text}, {\"conteudista\", type text}, {\"tematica\", type text}, {\"codigo_pessoa\", type text}, {\"sexo\", type text}, {\"idade\", Int64.Type}, {\"sit_matricula\", type text}, {\"poder\", type text}, {\"esfera\", type text}, {\"email_pessoa\", type text}, {\"telefone_pessoa\", Int64.Type}, {\"email_conteudista\", type text}}),",
                "    #\"Data Extraída1\" = Table.TransformColumns(#\"Tipo Alterado\",{{\"dt_matricula\", DateTime.Date, type date}}),",
                "    #\"Data Extraída\" = Table.TransformColumns(#\"Data Extraída1\",{{\"dt_matricula\", DateTime.Date, type date}, {\"dt_fim\", DateTime.Date, type date}})",
                "in",
                "    #\"Data Extraída\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_3175998e-eeff-41ff-ba63-e1dc1ee8d01d",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c620983c-7675-4aa8-ada4-9f3076e798d0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "050a4c91-0608-41a9-8672-59ba156bb274",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d7de7dad-0983-4da4-91c2-7e9a060d4bc6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e5227db9-5496-4b2f-a950-c7604906fb1c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8f942e16-6d67-4e3a-bdeb-df5637c162d1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "da31cc20-98a4-47a4-968a-3a5b10da48d4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c2c5bd46-e7c9-499e-bddf-129aa38a153c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "f58230ea-2d35-4f45-b941-15fcba8d6b09",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "263df7ca-5eca-4be0-b355-82177c4a5f51",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "0b76a62a-8b3e-44ae-9f13-10deba889449",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "db6c123b-3f5b-4ece-b063-8d4fd07d96ef",
                "ordinal": 3
              }
            ],
            "lineageTag": "0c729a04-e3af-40ba-a12d-c0142738834d"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "50b657e1-2cf5-45e8-bc84-0260f509daaf",
        "partitions": [
          {
            "name": "DateTableTemplate_3175998e-eeff-41ff-ba63-e1dc1ee8d01d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_630266ad-3423-414a-8136-5f9ed7acacf0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "eeb5db1f-53f5-4f0c-ad0e-3425e987b03b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "74c13dcc-f55d-4e96-a790-dadbbb3c15db",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "17690aab-7683-4abb-aab7-ae68d037251a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6c2c1c6b-aaac-44ce-b21e-05fbb88cfae2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "24cdcb34-43d6-4839-a33b-09bc8ba14b80",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b9ea0493-77d7-4c1b-808f-2308158437b7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1574e7ee-6a1b-4700-b43d-4828119cb575",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "d2b1218c-9071-4284-b5f5-dd34fd71ed16",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "5c659bd6-e60b-466f-acdc-ce4b2bb65a68",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "9f6d4e74-a6f2-4b8e-aac6-e2323d9bef5a",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "ce51cff9-2b36-4c7c-9f18-828e5c056094",
                "ordinal": 3
              }
            ],
            "lineageTag": "a88f4897-f73c-405c-850e-c20a1d3768a2"
          }
        ],
        "isHidden": true,
        "lineageTag": "c8555ba2-bd8c-4211-806c-6e04dab7820d",
        "partitions": [
          {
            "name": "LocalDateTable_630266ad-3423-414a-8136-5f9ed7acacf0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('amostra_evg'[dt_matricula])), 1, 1), Date(Year(MAX('amostra_evg'[dt_matricula])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_cc536f87-0eba-402d-b5c5-33db04e48925",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b2dc6e78-4e4c-4f23-80ba-7437636c4abb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "26221132-a95f-47e0-be00-a341fb54ca2d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a39590d4-ee38-4f3d-86aa-776185239f28",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "17c23b9e-36ea-4b61-b530-fbcda01f8ee4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "dc4bca9f-79c7-47e8-8a92-badd418a47bf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8544110e-2b65-4445-ad00-1fd99b3c9a60",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "401275cd-558c-4d81-baa8-c8489b46b914",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "70583fc9-6b4f-4b87-a8ac-3aaca1b32763",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "eafc6d67-43c6-459d-a303-b6251ed7203f",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "b8556711-23a1-4159-a7a2-f307b8f51120",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "749a9ec3-28ae-4b23-93b2-caa0373dd031",
                "ordinal": 3
              }
            ],
            "lineageTag": "252a308e-13ba-41b7-94e6-2b822cf00df1"
          }
        ],
        "isHidden": true,
        "lineageTag": "337a0e3a-a0e4-48d6-940e-160dd13670af",
        "partitions": [
          {
            "name": "LocalDateTable_cc536f87-0eba-402d-b5c5-33db04e48925",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('amostra_evg'[dt_fim])), 1, 1), Date(Year(MAX('amostra_evg'[dt_fim])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Dcalendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5ba2e36e-0a78-462c-8b5c-47fcc1d95a84",
            "sourceColumn": "data",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_dc1ef290-ff20-43ca-9327-1f008f9b1264"
                },
                "isDefault": true,
                "relationship": "39d9e91f-dff4-4d71-9fd8-1dd71ef822e0"
              }
            ]
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "719a10b3-784d-4378-a25f-92f4b7fb9a4f",
            "sourceColumn": "Ano",
            "summarizeBy": "sum"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9760a884-22dc-4c9e-89c7-3887dc0b05c1",
            "sourceColumn": "Mês",
            "summarizeBy": "sum"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "89a773ba-98b6-4f54-b1eb-aaafe25109ad",
            "sourceColumn": "Dia",
            "summarizeBy": "sum"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e9056eda-c75f-41fd-a0f0-32855be4410d",
            "sourceColumn": "Trimestre",
            "summarizeBy": "sum"
          },
          {
            "name": "Semana do Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "26e69e85-9ae1-43f0-a523-536484887a2f",
            "sourceColumn": "Semana do Ano",
            "summarizeBy": "sum"
          },
          {
            "name": "Dia da Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c0442917-54e2-4cca-8bb6-7c4f62e71e66",
            "sourceColumn": "Dia da Semana",
            "summarizeBy": "sum"
          },
          {
            "name": "Nome do Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00b23bb0-903c-4527-93f3-1d985d2e9492",
            "sourceColumn": "Nome do Dia",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "badbb8c4-7685-4f6a-99c8-46e9f46c8014",
        "partitions": [
          {
            "name": "Dcalendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = \"\",",
                "    dt_min = List.Min(amostra_evg[dt_matricula]),",
                "    dt_max = List.Max(amostra_evg[dt_matricula]),",
                "    ndias = Duration.Days(dt_max-dt_min)+1,",
                "    Personalizar1 = List.Dates(dt_min, ndias, #duration(1,0,0,0)),",
                "    #\"Convertido para Tabela\" = Table.FromList(Personalizar1, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Convertido para Tabela\",{{\"Column1\", type date}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado\",{{\"Column1\", \"data\"}}),",
                "    #\"Ano Inserido\" = Table.AddColumn(#\"Colunas Renomeadas\", \"Ano\", each Date.Year([data]), Int64.Type),",
                "    #\"Mês Inserido\" = Table.AddColumn(#\"Ano Inserido\", \"Mês\", each Date.Month([data]), Int64.Type),",
                "    #\"Trimestre Inserido\" = Table.AddColumn(#\"Mês Inserido\", \"Trimestre\", each Date.QuarterOfYear([data]), Int64.Type),",
                "    #\"Semana do Ano Inserida\" = Table.AddColumn(#\"Trimestre Inserido\", \"Semana do Ano\", each Date.WeekOfYear([data]), Int64.Type),",
                "    #\"Semana do Mês Inserida\" = Table.AddColumn(#\"Semana do Ano Inserida\", \"Semana do Mês\", each Date.WeekOfMonth([data]), Int64.Type),",
                "    #\"Dia Inserido\" = Table.AddColumn(#\"Semana do Mês Inserida\", \"Dia\", each Date.Day([data]), Int64.Type),",
                "    #\"Dia da Semana Inserido\" = Table.AddColumn(#\"Dia Inserido\", \"Dia da Semana\", each Date.DayOfWeek([data]), Int64.Type),",
                "    #\"Nome do Dia Inserido\" = Table.AddColumn(#\"Dia da Semana Inserido\", \"Nome do Dia\", each Date.DayOfWeekName([data]), type text),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Nome do Dia Inserido\",{\"Semana do Mês\"}),",
                "    #\"Dia Inserido1\" = Table.AddColumn(#\"Colunas Removidas\", \"Dia.1\", each Date.Day([data]), Int64.Type),",
                "    #\"Colunas Reordenadas\" = Table.ReorderColumns(#\"Dia Inserido1\",{\"data\", \"Ano\", \"Dia.1\", \"Mês\", \"Trimestre\", \"Semana do Ano\", \"Dia\", \"Dia da Semana\", \"Nome do Dia\"}),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Colunas Reordenadas\",{\"Dia.1\"}),",
                "    #\"Colunas Reordenadas1\" = Table.ReorderColumns(#\"Colunas Removidas1\",{\"data\", \"Ano\", \"Mês\", \"Dia\", \"Trimestre\", \"Semana do Ano\", \"Dia da Semana\", \"Nome do Dia\"})",
                "in",
                "    #\"Colunas Reordenadas1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_dc1ef290-ff20-43ca-9327-1f008f9b1264",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "79a34e05-d3df-4492-ac52-7cad5e2d30f8",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2260ddeb-9f82-40d2-adf3-75ba401c058e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "00cf7c0f-83d4-4f7c-a9f3-2b3275e87393",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "65f1da87-eff9-4449-81f6-b3fc321d6702",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fda1e863-5589-41de-b25c-a463ed32c4f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3f16865f-f88b-454b-bfda-095ae7931a08",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5b37c130-4abf-4622-9efb-eac8a9d640b5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "ef6c90df-ff00-4a5a-880a-c65963de39d4",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "03cc8fb4-0664-4e22-ba51-5ca80713e85a",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "5dac499f-9263-4667-b074-71e84cfd33a0",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "841727ff-ee40-4746-a1a5-ff3d7a566f88",
                "ordinal": 3
              }
            ],
            "lineageTag": "beed86b8-05c3-4796-af22-ccf212c9c88f"
          }
        ],
        "isHidden": true,
        "lineageTag": "e6bd3028-3997-4d13-b7e5-51b15b49ee64",
        "partitions": [
          {
            "name": "LocalDateTable_dc1ef290-ff20-43ca-9327-1f008f9b1264",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dcalendar'[data])), 1, 1), Date(Year(MAX('Dcalendar'[data])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Dim_turma",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "nome_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4e4c0b4-a61a-43e7-9a72-042299920e13",
            "sourceColumn": "nome_turma",
            "summarizeBy": "none"
          },
          {
            "name": "modalidade_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8b25847-0e76-478b-bb31-ddbe3861a28b",
            "sourceColumn": "modalidade_turma",
            "summarizeBy": "none"
          },
          {
            "name": "cod_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bdd142b8-7f0f-4e74-879e-14efa773dc44",
            "sourceColumn": "cod_turma",
            "summarizeBy": "none"
          },
          {
            "name": "sit_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4eae538a-8527-4acb-bc16-666869c0c679",
            "sourceColumn": "sit_turma",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bebe12c6-68a4-4410-9075-d287af9e2199",
        "partitions": [
          {
            "name": "Dim_turma",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = amostra_evg,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"cod_matricula\", \"nome_turma\", \"modalidade_turma\", \"cod_turma\", \"sit_turma\"}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Outras Colunas Removidas\",{\"cod_matricula\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_curso",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "cod_curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "40934d0d-a95e-45f5-bcd1-e7776fe48083",
            "sourceColumn": "cod_curso",
            "summarizeBy": "sum"
          },
          {
            "name": "nome_curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab5b7d5f-b73f-47c9-82d4-6b291a94aa6a",
            "sourceColumn": "nome_curso",
            "summarizeBy": "none"
          },
          {
            "name": "carga_horaria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "08fa9273-743f-42dd-bf57-3f8009a5d9c4",
            "sourceColumn": "carga_horaria",
            "summarizeBy": "sum"
          },
          {
            "name": "email_conteudista",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fea99a9-ba28-43ea-8fcf-761d6fba8ad2",
            "sourceColumn": "email_conteudista",
            "summarizeBy": "none"
          },
          {
            "name": "conteudista",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6ca0ef8-fbf1-48f7-92c1-8f062ae485ab",
            "sourceColumn": "conteudista",
            "summarizeBy": "none"
          },
          {
            "name": "tematica",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34914054-2801-4722-8937-d112f0402d1e",
            "sourceColumn": "tematica",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6f77177a-e358-4239-a0da-55210c399ba7",
        "partitions": [
          {
            "name": "Dim_curso",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = amostra_evg,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"cod_curso\", \"nome_curso\", \"carga_horaria\", \"email_conteudista\", \"conteudista\", \"tematica\"})",
                "in",
                "    #\"Outras Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_pessoa",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "codigo_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "acc786f9-ee90-44a2-a7c3-b498e4e99ecb",
            "sourceColumn": "codigo_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "sexo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0081937c-3f0a-4b59-97c1-10e00910cd3a",
            "sourceColumn": "sexo",
            "summarizeBy": "none"
          },
          {
            "name": "idade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2d643312-6f14-4324-96bd-625f3607d799",
            "sourceColumn": "idade",
            "summarizeBy": "sum"
          },
          {
            "name": "email_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8acb3792-cd8a-4ce2-8713-39229e2c5e64",
            "sourceColumn": "email_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "telefone_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "50abe9b6-7954-497a-b604-0a1a4543fc2f",
            "sourceColumn": "telefone_pessoa",
            "summarizeBy": "sum"
          },
          {
            "name": "instituicao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7fff9ad4-784e-4224-adc0-35199ab12b82",
            "sourceColumn": "instituicao",
            "summarizeBy": "none"
          },
          {
            "name": "nacionalidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef367075-7247-45cf-b736-fef0c462fe5a",
            "sourceColumn": "nacionalidade",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "486ab2d3-c52e-44b9-ba83-14e18e67a47b",
        "partitions": [
          {
            "name": "Dim_pessoa",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = amostra_evg,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"codigo_pessoa\", \"sexo\", \"idade\", \"email_pessoa\", \"telefone_pessoa\", \"instituicao\", \"nacionalidade\"})",
                "in",
                "    #\"Outras Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_poder",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "poder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "779760d1-553c-435d-a992-2e8042301579",
            "sourceColumn": "poder",
            "summarizeBy": "none"
          },
          {
            "name": "cod_poder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "70a655e7-35ed-4ea3-900a-458059cf110d",
            "sourceColumn": "cod_poder",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b6e0b8f3-4209-4a99-bff4-f8fee4f9d98f",
        "partitions": [
          {
            "name": "Dim_poder",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = amostra_evg,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"poder\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\"),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Duplicatas Removidas\", each ([poder] <> \"\")),",
                "    #\"Índice Adicionado\" = Table.AddIndexColumn(#\"Linhas Filtradas\", \"Índice\", 30, 3, Int64.Type),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Índice Adicionado\",{{\"Índice\", \"cod_poder\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_esfera",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "esfera",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c9392b7-3db7-4a3f-a8a2-4baeeb0b5e19",
            "sourceColumn": "esfera",
            "summarizeBy": "none"
          },
          {
            "name": "cod_esfera",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a47eceab-c801-4bbd-9e2c-a77f26252cd8",
            "sourceColumn": "cod_esfera",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "43106225-dbdb-4922-911b-d815d9929ce6",
        "partitions": [
          {
            "name": "Dim_esfera",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = amostra_evg,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"esfera\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\"),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Duplicatas Removidas\", each ([esfera] <> \"\")),",
                "    #\"Índice Adicionado\" = Table.AddIndexColumn(#\"Linhas Filtradas\", \"Índice\", 0, 1, Int64.Type),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Índice Adicionado\",{{\"Índice\", \"cod_esfera\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_localidade",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "municipio_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b584c52-e310-49f2-9f8d-38553646134a",
            "sourceColumn": "municipio_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "uf_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82828666-c38e-42a6-b07d-4ad082f8efef",
            "sourceColumn": "uf_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "Cod_localidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9fd6c6f3-5308-4aa8-aa48-6d857d47c2d7",
            "sourceColumn": "Cod_localidade",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f3b29435-e216-4e92-bd51-e48c39b57b84",
        "partitions": [
          {
            "name": "Dim_localidade",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = amostra_evg,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"municipio_pessoa\", \"uf_pessoa\"}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Outras Colunas Removidas\", each ([municipio_pessoa] <> \"\")),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Linhas Filtradas\", {\"municipio_pessoa\"}),",
                "    #\"Índice Adicionado\" = Table.AddIndexColumn(#\"Duplicatas Removidas\", \"Índice\", 0, 1, Int64.Type),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Índice Adicionado\",{{\"Índice\", \"Cod_localidade\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "F_matricula",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "cod_matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84c58c2d-6d85-43a9-b919-451048434ffd",
            "sourceColumn": "cod_matricula",
            "summarizeBy": "none"
          },
          {
            "name": "dt_matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2e4b13da-ad07-481d-8cf6-cf189840d82e",
            "sourceColumn": "dt_matricula",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_6b7251f7-6662-49c8-b1a3-9d7213045187"
                },
                "isDefault": true,
                "relationship": "042f49a3-e63c-4f5d-821b-0744c4ed9992"
              }
            ]
          },
          {
            "name": "cod_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "89687faf-18b0-4963-a541-204368936635",
            "sourceColumn": "cod_turma",
            "summarizeBy": "none"
          },
          {
            "name": "cod_curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fd9bc34d-f5e2-415c-89de-885fdbe58f81",
            "sourceColumn": "cod_curso",
            "summarizeBy": "sum"
          },
          {
            "name": "dt_fim",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "52160bc5-086c-4e1d-a16b-d9c9642af524",
            "sourceColumn": "dt_fim",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_b3816c51-0a65-40e0-a5c6-5dc2be8a9148"
                },
                "isDefault": true,
                "relationship": "a7e73bcb-0777-43e0-9805-e3fd9cbeed60"
              }
            ]
          },
          {
            "name": "sit_matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06401c30-4f90-42d2-9739-0425509e25ed",
            "sourceColumn": "sit_matricula",
            "summarizeBy": "none"
          },
          {
            "name": "codigo_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0583ecc4-b9e5-432b-a9cd-0d0d07bb57cb",
            "sourceColumn": "codigo_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "cod_poder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3c200b12-376c-4d19-8fbf-35298ca24283",
            "sourceColumn": "cod_poder",
            "summarizeBy": "none"
          },
          {
            "name": "Cod_localidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e7e24fd-77d0-47ef-a906-d3befacde02c",
            "sourceColumn": "Cod_localidade",
            "summarizeBy": "none"
          },
          {
            "name": "cod_esfera",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "26d3f489-f442-4e52-b82c-fd4215bf7456",
            "sourceColumn": "cod_esfera",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f1dd39b4-eb49-47fc-a0fa-08272fd1eadd",
        "partitions": [
          {
            "name": "F_matricula",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = amostra_evg,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"cod_matricula\", \"dt_matricula\", \"cod_turma\", \"cod_curso\", \"dt_fim\", \"sit_matricula\", \"codigo_pessoa\"}),",
                "    #\"Índice Adicionado\" = Table.AddIndexColumn(#\"Outras Colunas Removidas\", \"Índice\", 0, 1, Int64.Type),",
                "    #\"Índice Adicionado1\" = Table.AddIndexColumn(#\"Índice Adicionado\", \"Índice.1\", 30, 3, Int64.Type),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Índice Adicionado1\", {\"Índice.1\"}, Dim_poder, {\"cod_poder\"}, \"Dim_poder\", JoinKind.LeftOuter),",
                "    #\"Dim_poder Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"Dim_poder\", {\"cod_poder\"}, {\"cod_poder\"}),",
                "    #\"Consultas Mescladas1\" = Table.NestedJoin(#\"Dim_poder Expandido\", {\"Índice\"}, Dim_localidade, {\"Cod_localidade\"}, \"Dim_localidade\", JoinKind.LeftOuter),",
                "    #\"Consultas Mescladas2\" = Table.NestedJoin(#\"Consultas Mescladas1\", {\"Índice\"}, Dim_esfera, {\"cod_esfera\"}, \"Dim_esfera\", JoinKind.LeftOuter),",
                "    #\"Dim_localidade Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas2\", \"Dim_localidade\", {\"Cod_localidade\"}, {\"Cod_localidade\"}),",
                "    #\"Dim_esfera Expandido\" = Table.ExpandTableColumn(#\"Dim_localidade Expandido\", \"Dim_esfera\", {\"cod_esfera\"}, {\"cod_esfera\"}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Dim_esfera Expandido\",{\"Índice\", \"Índice.1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_6b7251f7-6662-49c8-b1a3-9d7213045187",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "71e868ab-4b49-4ee3-b316-c1b76e112a6a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "becfb329-0d1e-4109-95b8-8a6da7d701ef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6f1add08-0847-4e98-9d2e-9dc0f8481450",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ff835dbb-c80f-4807-9550-65ecb75ff770",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "707cb6a0-f964-4f2b-9776-922782491e40",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "18d0d4b6-3767-47f8-a983-5a2d981837c5",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "62940cd7-cf9d-440d-a731-0c8bc75acb44",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "852a5a8f-3768-4254-b358-87fbc23cc463",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "64db3d26-4292-460d-937c-8fd294aa99d8",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "79a42783-40cc-42dc-af8d-7890a3134e7a",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "d0a1acae-bc5c-4623-ad88-de5245639552",
                "ordinal": 3
              }
            ],
            "lineageTag": "256db160-abbd-4cfd-872f-eeb6652100fe"
          }
        ],
        "isHidden": true,
        "lineageTag": "5c5b403d-609c-4718-8bdb-8acecf82b26e",
        "partitions": [
          {
            "name": "LocalDateTable_6b7251f7-6662-49c8-b1a3-9d7213045187",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('F_matricula'[dt_matricula])), 1, 1), Date(Year(MAX('F_matricula'[dt_matricula])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_b3816c51-0a65-40e0-a5c6-5dc2be8a9148",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "119608fa-49b4-4ffe-9b9d-ed2c1088ce6b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "47b1eee3-fab0-4c37-b865-24d024d3c348",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "42a27f29-a345-44e2-9d1d-28199184726a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "77025128-e910-48b5-bc9b-e85663b8c45c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "40a7707c-0137-4501-a2c1-d19742ad645a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a14974fe-e2ab-4e83-84af-428894d038ad",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a87b63ba-886b-4c3e-9c55-185edce524c7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "56ded72e-5181-4fc1-9cd8-b02adb5026bb",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "94a68bfd-9123-4037-a3a9-b446bddb09cb",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "0221fb3a-2f6b-41f6-adb7-162d3c600e7f",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "1eae1f89-eeb3-4207-8b71-07de5a675d90",
                "ordinal": 3
              }
            ],
            "lineageTag": "f21653f0-1b1a-4b97-801c-67d2f9c99539"
          }
        ],
        "isHidden": true,
        "lineageTag": "a617254b-d3c5-43af-a52b-48fb4e2374cc",
        "partitions": [
          {
            "name": "LocalDateTable_b3816c51-0a65-40e0-a5c6-5dc2be8a9148",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('F_matricula'[dt_fim])), 1, 1), Date(Year(MAX('F_matricula'[dt_fim])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}